spring.application.name=CRUD_springoot
spring.datasource.url=jdbc:mysql://localhost:3306/kayal
spring.datasource.username=root
spring.datasource.password=kayal@01
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
